### ISSUE TITLE
登陆太强制性了

### ISSUE THREAD

**Issue by sygdtv** [ahe-meow/Commonwealth-Empowerment#1]
让使用者有个选择吧，扫码、钉钉

**Comment by dxq0739** [comment]
> 让使用者有个选择吧，扫码、钉钉

怎么输入密文呀，打开只显示浏览器呀

**Comment by sygdtv** [comment]
nkzkzdtyjyyjxzpmdtycyk这个是密文，自己修改一下。在任意地方输。

**Comment by ahe-meow** [comment]
> 让使用者有个选择吧，扫码、钉钉

已更新选择项
