### ISSUE TITLE
进度条和记分部分重合

### ISSUE THREAD

**Issue by sygdtv** [ahe-meow/Commonwealth-Empowerment#3]
Gui Add, ActiveX, xm w980 h640 vWB disabled, Shell.Explorer.2
改成620正常

**Comment by ahe-meow** [comment]
> Gui Add, ActiveX, xm w980 h640 vWB disabled, Shell.Explorer.2
> 改成620正常

我在好几台机器上测试都没发现这个问题。能不能截图来看下，顺便说明屏幕分辨率

**Comment by AmberisMyShiba** [comment]
我也遇到类似问题。在笔记本上分辨率是1366*768

[
![无标题](https://user-images.githubusercontent.com/20527882/60932714-d6701b00-a2f1-11e9-9c08-8af433214978.jpg)
](url)


> Gui Add, Edit, w930 r1 vURL, http://www.baidu.com/
> Gui Add, Button, x+6 yp-2 w44 Default, Nav
> Gui Add, ActiveX, xm w980 **h620** vWB1, Shell.Explorer

640改为620正常了
